### ISSUE TITLE
Error when saving 'Enable Seeding' to true form UI

### ISSUE THREAD

**Issue by pratikbalar** [boypt/simple-torrent#114]
getting below error when trying to save just `Enable Seeding` to `true` from UI
```log
2021/04/17 19:33:49 ############# SimpleTorrent ver[1.2.18] #############
2021/04/17 19:33:49 [viper Config] Config File "cloud-torrent" Not Found in "[/etc/cloud-torrent /etc /root/.cloud-torrent /]"
2021/04/17 19:33:49 [config] selected config file:  ./cloud-torrent.yaml
2021/04/17 19:33:49 [config] config file written:  ./cloud-torrent.yaml exists: false dirchanged true
2021/04/17 19:33:49 Torrent Watcher: watching torrent file in /torrents
2021/04/17 19:33:49 Listening at http://0.0.0.0:3000
2021/04/17 19:33:49 fetchSearchConfig: loading search config from https://raw.githubusercontent.com/boypt/simple-torrent/master/scraper-config.json
2021/04/17 19:33:49 UpdateTrackers: loading trackers from https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
2021/04/17 19:33:55 UpdateTrackers: loaded 20 trackers 
2021/04/17 19:33:55 Loaded new search providers
2021-04-17T19:34:20+0000 NONE  client.go:371: dht server on [::]:50007 completed bootstrap (dht.TraversalStats{NumAddrsTried:9, NumResponses:0})
2021/04/17 19:34:47 config updated  EnableSeeding :  false  ->  true
2021/04/17 19:34:47 [api] config saved
2021/04/17 19:34:47 Configure: old client closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc922f8]

goroutine 25 [running]:
github.com/anacrolix/torrent.(*Client).ConnStats(...)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.25.1/client.go:1563
github.com/jpillora/cloud-torrent/engine.(*Engine).ConnStat(...)
        /root/cloud-torrent/engine/engine.go:552
github.com/jpillora/cloud-torrent/server.(*Server).backgroundRoutines.func2(0xc0002bc400)
        /root/cloud-torrent/server/server_bg.go:47 +0x118
created by github.com/jpillora/cloud-torrent/server.(*Server).backgroundRoutines
        /root/cloud-torrent/server/server_bg.go:42 +0x9f
```

**Comment by boypt** [comment]
should be fixed in latest release.
