### ISSUE TITLE
panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by mincaeuro** [boypt/simple-torrent#120]
Hi,

just wanna update to the latest version, but during build I'm getting this error (armhf CPU):
Any help?

thanks
```
goroutine 340 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x19de104, 0x1, 0x0, 0x0, 0x0)
        runtime/internal/atomic/asm_arm.s:233 +0x14
github.com/anacrolix/dht/v2.(*traversal).wrapQuery(0x19de0c4, 0xd8e2c0, 0x19d68e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:115 +0x44
github.com/anacrolix/dht/v2.(*traversal).run.func1.1(0x15a94e0)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:156 +0x30
github.com/anacrolix/dht/v2.(*traversal).beginQuery.func1.1(0x0)
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:179 +0x98
github.com/anacrolix/dht/v2.(*Server).beginQuery.func1.1()
        github.com/anacrolix/dht/v2@v2.9.1/server.go:745 +0x24
created by github.com/anacrolix/dht/v2.(*traversal).run
        github.com/anacrolix/dht/v2@v2.9.1/traversal.go:164 +0x88
```

**Comment by boypt** [comment]
they fix the problem but haven't release a new version.

in the go.mod, replace the dht lib version:

```
replace 	github.com/anacrolix/dht/v2 => github.com/anacrolix/dht/v2 v2.9.2-0.20210527235055-9013a10a0c7d
```

the latest lib in our lib is fixed.
