### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by yiguihai** [boypt/simple-torrent#90]
在小米8手机 android10 上不能用，一访问网页就自动关闭退出然后显示以下信息
```Shell
$ ./cloud-torrent_android_arm64
2020/10/03 10:48:30 ############# SimpleTorrent ver[1.2.11] #############
2020/10/03 10:48:30 Using local static files
2020/10/03 10:48:30 [config] selected config file:  /data/data/com.termux/files/home/simple-torrent/cloud-torrent.yaml
2020/10/03 10:48:30 Listening at http://0.0.0.0:3000
2020/10/03 10:48:30 fetchSearchConfig: loading search config from https://raw.githubusercontent.com/boypt/simple-torrent/master/scraper-config.json
2020/10/03 10:48:30 [Watcher] /data/data/com.termux/files/home/simple-torrent/torrents is not dir
2020/10/03 10:48:30 UpdateTrackers: loading trackers from https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
2020-10-03T10:48:30+0000 NONE  server.go:923: dht server on 0.0.0.0:50007: falling back on starting nodes
2020-10-03T10:48:30+0000 NONE  server.go:923: dht server on [::]:50007: falling back on starting nodes
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.utorrent.com:6881": lookup router.utorrent.com on [::1]:53: read udp [::1]:45481->[::1]:53: read: connection refused
2020/10/03 10:48:30 [fetchSearchConfig] Get "https://raw.githubusercontent.com/boypt/simple-torrent/master/scraper-config.json": dial tcp: lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:44562->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.bittorrent.com:6881": lookup router.bittorrent.com on [::1]:53: read udp [::1]:44925->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.utorrent.com:6881": lookup router.utorrent.com on [::1]:53: read udp [::1]:39600->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.transmissionbt.com:6881": lookup dht.transmissionbt.com on [::1]:53: read udp [::1]:40596->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.aelitis.com:6881": lookup dht.aelitis.com on [::1]:53: read udp [::1]:42640->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.bittorrent.com:6881": lookup router.bittorrent.com on [::1]:53: read udp [::1]:41548->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.transmissionbt.com:6881": lookup dht.transmissionbt.com on [::1]:53: read udp [::1]:41290->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.silotis.us:6881": lookup router.silotis.us on [::1]:53: read udp [::1]:37615->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.libtorrent.org:25401": lookup dht.libtorrent.org on [::1]:53: read udp [::1]:42600->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  client.go:330: error bootstrapping dht: getting starting nodes: nothing resolved
2020-10-03T10:48:30+0000 NONE  client.go:332: dht server on 0.0.0.0:50007 completed bootstrap (dht.TraversalStats{NumAddrsTried:0, NumResponses:0})
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.aelitis.com:6881": lookup dht.aelitis.com on [::1]:53: read udp [::1]:48200->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "router.silotis.us:6881": lookup router.silotis.us on [::1]:53: read udp [::1]:41205->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  dht.go:109: error looking up "dht.libtorrent.org:25401": lookup dht.libtorrent.org on [::1]:53: read udp [::1]:48350->[::1]:53: read: connection refused
2020-10-03T10:48:30+0000 NONE  client.go:330: error bootstrapping dht: getting starting nodes: nothing resolved
2020-10-03T10:48:30+0000 NONE  client.go:332: dht server on [::]:50007 completed bootstrap (dht.TraversalStats{NumAddrsTried:0, NumResponses:0})
2020-10-03T10:48:32+0000 NONE  portfwd.go:30: discovered 0 upnp devices
panic: runtime error: index out of range [0] with length 0

goroutine 34 [running]:
github.com/jpillora/cloud-torrent/server.(*stats).loadStats(0x40001f8a20, 0x40000a5bc0, 0x39)
        /data/data/com.termux/files/home/simple-torrent/server/server_stats.go:33 +0x158
github.com/jpillora/cloud-torrent/server.(*Server).backgroundRoutines.func2(0x40001f8700)
        /data/data/com.termux/files/home/simple-torrent/server/server_bg.go:46 +0xb4
created by github.com/jpillora/cloud-torrent/server.(*Server).backgroundRoutines
        /data/data/com.termux/files/home/simple-torrent/server/server_bg.go:42 +0x84
$
```
https://github.com/boypt/simple-torrent/blob/master/server/server_stats.go#L32-L34 看了一下这里没有返回数据判断，引用库问题修改后能用了。

**Comment by yiguihai** [comment]
返回类型为 float64 注释掉代码与引用库。强行返回，反正也不能用
